import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header/header";
import Footer from "@/components/ui/footer/footer";
import "font-awesome/css/font-awesome.min.css"; // For Font Awesome 4.x
import Head from "next/head";

const geistSans = Geist({
  variable: "--Arial",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="./font-awesome.min.css" />
      </Head>
      <body className={`${geistSans.variable} antialiased`}>
        <Header />
        <div className="app">
          <div className="app-main-inner overflow-visible h-auto">
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
